services:
  php:
    build: ./php
    container_name: tax-calculator-php
    volumes:
      - ./../:/var/www
    networks:
      - app-network

  mysql:
    build: ./mysql
    container_name: tax-calculator-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tax_calculator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  mariadb:
    build: ./mariadb
    container_name: tax-calculator-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: tax_calculator
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
    build: ./phpmyadmin
    container_name: tax-calculator-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8081:80
    depends_on:
      - mariadb
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: tax-calculator-nginx
    volumes:
      - ./../:/var/www
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
    - php

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mariadb-data:
